// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSAqb2IXEk-BEbKj5NatHLJDBDW_x3vIE',
    appId: '1:179443986872:web:563e15229b5576cbb6df4d',
    messagingSenderId: '179443986872',
    projectId: 'daybyday-d71bd',
    authDomain: 'daybyday-d71bd.firebaseapp.com',
    storageBucket: 'daybyday-d71bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAdhzZrUYdaJHKcSQA3EfQWQS_7ngtL3w',
    appId: '1:179443986872:android:2ba2723143c3275db6df4d',
    messagingSenderId: '179443986872',
    projectId: 'daybyday-d71bd',
    storageBucket: 'daybyday-d71bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtXG2LW3xVCesDkfwneSw7BZIy91RQVJ8',
    appId: '1:179443986872:ios:348e472b55106ee7b6df4d',
    messagingSenderId: '179443986872',
    projectId: 'daybyday-d71bd',
    storageBucket: 'daybyday-d71bd.appspot.com',
    iosClientId: '179443986872-9dagko9cgo1agpaeeke9ftplok11slob.apps.googleusercontent.com',
    iosBundleId: 'com.example.daybyday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtXG2LW3xVCesDkfwneSw7BZIy91RQVJ8',
    appId: '1:179443986872:ios:348e472b55106ee7b6df4d',
    messagingSenderId: '179443986872',
    projectId: 'daybyday-d71bd',
    storageBucket: 'daybyday-d71bd.appspot.com',
    iosClientId: '179443986872-9dagko9cgo1agpaeeke9ftplok11slob.apps.googleusercontent.com',
    iosBundleId: 'com.example.daybyday',
  );
}
